'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {openStore}=require('../src/storage.cjs'),ledger=require('../src/domain/ledger.cjs'),math=require('../assets/cashflow-math.js');
const {createBackup,checksum,inspectSnapshot}=require('../src/backup.cjs'),{restore}=require('../tools/restore.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'actual-correction-')),store=openStore(path.join(dir,'db.sqlite')),api=ledger(store,{today:()=> '2026-12-31'});t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});store.db.exec("INSERT INTO users VALUES('admin','合成管理者','test-only','admin','2026-01-01')");for(const id of ['a','b'])api.post({action:'saveAccount',id,bank:'合成銀行',branch:'同じ支店',accountNumber:id==='a'?'001':'002',type:'普通',balance:1000000,balanceDate:'2026-03-31'});return {store,api,dir};}
function manual(b,extra={},planned=true){const row={id:'m',type:'出金',account:'a',plannedDate:'2026-04-10',plannedAmount:10000,partner:'取引先',description:'内容',memo:'合成',...extra};if(planned)b.api.post({action:'saveTransaction',...row});b.api.post({action:'saveTransaction',...row,status:'確定',actualDate:row.plannedDate,actualAmount:row.plannedAmount,expectedUpdatedAt:b.store.find('cashflow_transactions',row.id)?.updatedAt});return b.store.find('cashflow_transactions',row.id);}
function body(b,id='m',extra={},action='correctActual'){const d=b.api.get('getActualDetail',{id}),t=d.transaction;return {action,id,requestId:randomUUID(),expectedUpdatedAt:t.updatedAt,reason:'通帳を照合して訂正',confirmed:true,...(d.master?{expectedParentVersion:d.master.version}:d.debt?{expectedParentVersion:d.debt.updatedAt}:{}),...(action==='correctActual'?{actualDate:t.actualDate,actualAmount:t.actualAmount,type:t.type,account:t.account,partner:t.partner||'',description:t.description||'',memo:t.memo||'',...(d.occurrence?.kind==='loan'?{actualPrincipal:d.leg.actualPrincipal,actualInterest:d.leg.actualInterest}:{})}:{}),...extra};}
const post=(b,v)=>b.api.post(v,'admin');
const balance=(b,id,date='2026-07-31')=>math.actualAt(b.store.find('accounts',id),b.store.all('cashflow_transactions'),date);
const all=b=>Object.fromEntries(b.store.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(({name})=>[name,b.store.db.prepare('SELECT * FROM '+name+' ORDER BY 1').all()]));
for(const [name,change,expected]of [
 ['amount',{actualAmount:8000},[992000,1000000]],['type',{type:'入金'},[1010000,1000000]],['account',{account:'b'},[1000000,990000]],['date',{actualDate:'2026-08-01'},[1000000,1000000]],['zero',{actualAmount:0},[1000000,1000000]]
])test('manual correction recalculates '+name,t=>{const b=setup(t);manual(b);post(b,body(b,'m',change));assert.equal(balance(b,'a'),expected[0]);assert.equal(balance(b,'b'),expected[1]);assert.equal(b.store.find('cashflow_transactions','m').status,'確定');if(name==='date')assert.equal(balance(b,'a','2026-08-31'),990000);});
test('cancel keeps ID and complete before/after history, excludes actuals and cannot be physically deleted or resurrected',t=>{const b=setup(t),before=manual(b);post(b,body(b,'m',{},'cancelActual'));const d=b.api.get('getActualDetail',{id:'m'});assert.equal(d.transaction.status,'取消');assert.equal(balance(b,'a'),1000000);assert.deepEqual(d.history[0].before.transaction,before);assert.equal(d.history[0].actorName,'合成管理者');assert.equal(d.history[0].after.transaction.actualAmount,null);assert.throws(()=>b.api.post({action:'deleteRecord',sheet:'cashflow_transactions',id:'m',expectedUpdatedAt:d.transaction.updatedAt}),/物理削除/);assert.throws(()=>b.api.post({action:'saveTransaction',...d.transaction,status:'予定',expectedUpdatedAt:d.transaction.updatedAt}),/履歴/);assert.throws(()=>b.store.db.prepare("DELETE FROM transaction_revisions").run(),/immutable/);assert.throws(()=>b.store.db.prepare("UPDATE transaction_origins SET kind='direct'").run(),/immutable/);});
test('reopen restores original plan including original account and amount, can confirm again without duplicate',t=>{const b=setup(t);manual(b);post(b,body(b,'m',{account:'b',actualAmount:8000,description:'訂正'}));post(b,body(b,'m',{},'reopenActual'));let r=b.store.find('cashflow_transactions','m');assert.equal(r.status,'予定');assert.equal(r.account,'a');assert.equal(r.plannedAmount,10000);assert.equal(r.description,'内容');assert.equal(balance(b,'b'),1000000);b.api.post({action:'saveTransaction',...r,expectedUpdatedAt:r.updatedAt,status:'確定',actualDate:'2026-05-01',actualAmount:9000});assert.equal(b.store.all('cashflow_transactions').length,1);assert.equal(balance(b,'a'),991000);assert.equal(b.api.get('getActualDetail',{id:'m'}).history.length,2);});
test('new direct actual without a prior plan cannot reopen even when technical planned fields exist',t=>{const b=setup(t);manual(b,{},false);assert.equal(b.api.get('getActualDetail',{id:'m'}).canReopen,false);assert.throws(()=>post(b,body(b,'m',{},'reopenActual')),/元予定/);});
test('changes before bank baseline require acknowledgment and never rewrite baseline',t=>{const b=setup(t);manual(b);const p=body(b,'m',{actualDate:'2026-03-31'});assert.throws(()=>post(b,p),/基準日/);post(b,{...p,acknowledgeBaseline:true});assert.equal(balance(b,'a'),1000000);assert.equal(b.store.find('accounts','a').balance,1000000);assert.equal(balance(b,'a','2026-03-30'),1010000);});
test('retry is idempotent, altered retry and stale concurrent write are rejected',t=>{const b=setup(t);manual(b);const p=body(b,'m',{actualAmount:8000}),stale=body(b,'m',{actualAmount:7000});post(b,p);const before=all(b);assert.equal(post(b,p).duplicate,true);assert.deepEqual(all(b),before);assert.throws(()=>post(b,{...p,actualAmount:1}),/再送/);assert.throws(()=>post(b,stale),/更新/);assert.deepEqual(all(b),before);});
for(const [name,change]of [['negative',{actualAmount:-1}],['fraction',{actualAmount:1.1}],['overflow',{actualAmount:Number.MAX_SAFE_INTEGER+1}],['future',{actualDate:'2027-01-01'}],['invalid date',{actualDate:'2026-02-30'}],['missing account',{account:'missing'}],['reason',{reason:''}],['confirmation',{confirmed:false}],['provenance tampering',{sourceId:'other'}],['plan tampering',{plannedAmount:3}]])test('reject invalid correction '+name+' atomically',t=>{const b=setup(t);manual(b);const before=all(b);assert.throws(()=>post(b,body(b,'m',change)));assert.deepEqual(all(b),before);});
test('administrator required even on direct service calls',t=>{const b=setup(t);manual(b);const before=all(b);assert.throws(()=>b.api.post(body(b),'unknown'),/管理者/);assert.deepEqual(all(b),before);});
test('injected audit failure rolls back transaction, origin and history together',t=>{const b=setup(t);manual(b);const before=all(b),audit=b.store.audit;b.store.audit=()=>{throw Error('Injected audit failure');};assert.throws(()=>post(b,body(b,'m',{actualAmount:8000})),/Injected/);b.store.audit=audit;assert.deepEqual(all(b),before);});
function debt(b,kind){const r=kind==='receivable';b.api.post({action:r?'saveReceivable':'savePayable',id:'d',partner:'合成先',invoiceDate:'2026-04-01',occDate:'2026-04-01',dueDate:'2026-04-10',amount:10000,account:'a'});for(const [pid,amount]of [['p1',6000],['p2',4000]])b.api.post({action:r?'confirmReceivable':'confirmPayable',id:'d',paymentId:pid,date:'2026-04-10',amount,account:'a',expectedUpdatedAt:b.store.find(r?'receivables':'payables','d').updatedAt});}
for(const kind of ['receivable','payable'])test(kind+' partial payment correction/cancel/reopen keeps remaining schedule consistent',t=>{const b=setup(t);debt(b,kind);post(b,body(b,'pay_p1',{actualAmount:5000,account:'b'}));const table=kind==='receivable'?'receivables':'payables';assert.equal(b.store.find(table,'d').paidAmount,9000);assert.equal(b.store.find('cashflow_transactions','cf_d').plannedAmount,1000);assert.throws(()=>post(b,body(b,'pay_p1',{actualAmount:7000})),/総額/);post(b,body(b,'pay_p1',{},'cancelActual'));assert.equal(b.store.find(table,'d').paidAmount,4000);post(b,body(b,'pay_p2',{},'reopenActual'));assert.equal(b.store.find(table,'d').paidAmount,0);assert.equal(b.store.find('cashflow_transactions','cf_d').plannedAmount,10000);assert.equal(b.store.all('cashflow_transactions').filter(t=>t.status==='予定').length,1);assert.throws(()=>b.api.post({action:'deleteRecord',sheet:table,id:'d',expectedUpdatedAt:b.store.find(table,'d').updatedAt}),/決済実績/);inspectSnapshot(b.store.filename);});
test('debt parent stale version and reversed type rejected',t=>{const b=setup(t);debt(b,'payable');assert.throws(()=>post(b,body(b,'pay_p1',{expectedParentVersion:'old'})),/元予定/);assert.throws(()=>post(b,body(b,'pay_p1',{type:'入金'})),/区分/);});
function schedule(b,mode='split',kind='loan'){
 const req={action:'scheduleSave',id:'s',requestId:randomUUID(),name:'合成借入',kind,account:'a',partner:'合成先',holidayRule:'none',defaultDebitMode:mode,principalStartMode:'existing',principalBalanceDate:'2026-03-31',principalOpeningBalance:3850000,rows:[{id:'r',nominalDate:'2026-04-30',plannedPrincipal:100000,plannedInterest:12345,plannedAmount:123450}]};b.api.post(req);return b.api.get('getPaymentSchedules').data[0];
}
function settle(b,component){const m=b.api.get('getPaymentSchedules').data[0],l=m.occurrences[0].legs.find(l=>l.component===component);b.api.post({action:'scheduleConfirm',requestId:randomUUID(),id:l.id,expectedVersion:m.version,actualDate:'2026-04-30',actualPrincipal:100000,actualInterest:12345,actualAmount:123450,settled:true});return l.transactionId;}
test('combined loan correction updates bank total, principal and interest; reopen reverses actuals only',t=>{const b=setup(t);schedule(b,'combined');const id=settle(b,'total');post(b,body(b,id,{actualPrincipal:90000,actualInterest:12000,actualAmount:102000,account:'b'}));let m=b.api.get('getPaymentSchedules').data[0];assert.equal(m.principalRemaining,3760000);assert.equal(m.interestPaid,12000);assert.equal(balance(b,'a'),1000000);assert.equal(balance(b,'b'),898000);assert.equal(m.occurrences[0].status,'支払済');post(b,body(b,id,{},'reopenActual'));m=b.api.get('getPaymentSchedules').data[0];assert.equal(m.principalRemaining,3850000);assert.equal(m.interestPaid,0);assert.equal(m.occurrences[0].status,'未支払');assert.equal(b.store.find('cashflow_transactions',id).account,'a');settle(b,'total');assert.equal(b.api.get('getPaymentSchedules').data[0].principalRemaining,3750000);});
test('split loan: only principal corrected, interest untouched; cancelling principal preserves paid interest and partial state',t=>{const b=setup(t);schedule(b);const principal=settle(b,'principal'),interest=settle(b,'interest'),old=b.store.find('cashflow_transactions',interest);post(b,body(b,principal,{actualPrincipal:90000,actualAmount:90000}));assert.deepEqual(b.store.find('cashflow_transactions',interest),old);post(b,body(b,principal,{},'cancelActual'));const m=b.api.get('getPaymentSchedules').data[0];assert.equal(m.principalRemaining,3850000);assert.equal(m.interestPaid,12345);assert.equal(m.occurrences[0].status,'一部支払・残予定取消');assert.equal(balance(b,'a'),987655);});
test('split loan: reopen interest yields principal paid, interest pending; reconfirm completes',t=>{const b=setup(t);schedule(b);settle(b,'principal');const id=settle(b,'interest');post(b,body(b,id,{},'reopenActual'));let m=b.api.get('getPaymentSchedules').data[0];assert.equal(m.principalRemaining,3750000);assert.equal(m.interestPaid,0);assert.equal(m.occurrences[0].status,'一部支払');settle(b,'interest');assert.equal(b.api.get('getPaymentSchedules').data[0].occurrences[0].status,'支払済');});
test('loan basis boundary uses actual principal date, historical base not edited',t=>{const b=setup(t);schedule(b,'combined');const id=settle(b,'total');post(b,body(b,id,{actualDate:'2026-03-31',acknowledgeBaseline:true}));const m=b.api.get('getPaymentSchedules').data[0];assert.equal(m.principalRemaining,3850000);assert.equal(m.interestPaid,12345);assert.equal(m.principalOpeningBalance,3850000);});
test('loan rejects component mismatch, nonmatching total, source type changes and stale parent',t=>{const b=setup(t);schedule(b);const id=settle(b,'principal');for(const changes of [{actualInterest:1,actualAmount:100001},{actualAmount:99999},{type:'入金'},{expectedParentVersion:1}]){const before=all(b);assert.throws(()=>post(b,body(b,id,changes)));assert.deepEqual(all(b),before);}});
test('variable nonloan actual correction changes amount and keeps plan',t=>{const b=setup(t);schedule(b,'single','lease');const id=settle(b,'total');post(b,body(b,id,{actualAmount:122000}));assert.equal(balance(b,'a'),878000);assert.equal(b.store.find('cashflow_transactions',id).plannedAmount,123450);});
test('fixed expense cancellation cannot be regenerated; reopened original is protected from master sync',t=>{const b=setup(t);const f={action:'saveFixedExpense',scope:'all',id:'f',name:'合成固定',payee:'先',amount:10000,day:10,startMonth:'2026-04',endMonth:'2026-04',account:'a',holidayRule:'none'};b.api.post(f);const id='fx_f_202604';let r=b.store.find('cashflow_transactions',id);b.api.post({action:'saveTransaction',...r,expectedUpdatedAt:r.updatedAt,status:'確定',actualDate:'2026-04-10',actualAmount:10000});post(b,body(b,id,{},'reopenActual'));b.api.post({...f,scope:'all',amount:20000,expectedUpdatedAt:b.store.find('fixed_expenses','f').updatedAt});assert.equal(b.store.find('cashflow_transactions',id).plannedAmount,10000);r=b.store.find('cashflow_transactions',id);b.api.post({action:'saveTransaction',...r,expectedUpdatedAt:r.updatedAt,status:'確定',actualDate:'2026-04-10',actualAmount:10000});post(b,body(b,id,{},'cancelActual'));b.api.replenish();assert.equal(b.store.find('cashflow_transactions',id).status,'取消');});
test('corrected data used consistently for period totals and actual Excel workbook',t=>{const b=setup(t);manual(b);post(b,body(b,'m',{actualAmount:8000,description:'=1+1'}));const periods=b.api.get('getCashflowPeriod',{start:'2026-04',end:'2026-07',accounts:'a,b',mode:'actual',day:'2026-12-31'}).periods;assert.equal(periods[0].totals.a.closing,992000);assert.equal(periods[3].totals.a.closing,992000);const {createFrontend}=require('./helpers.cjs'),f=createFrontend();f.app.accounts=b.store.all('accounts');f.app.selectedAccountIds=['a','b'];f.app.currentMonth='2026-04';f.app.currentMonthData=b.store.all('cashflow_transactions');f.app.viewMode='actual';f.context.renderCashflowTable();assert.match(f.node('cashflowTableBody').innerHTML,/8,000/);f.context.exportCashflowToExcel();const XLSX=require('../assets/vendor/xlsx.full.min.js'),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(f.captured.rows),'実績');const file=XLSX.read(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),{type:'buffer'});assert.ok(Object.values(file.Sheets['実績']).some(c=>c?.v==='=1+1'&&!c.f));});
test('real backup/restore retains histories, source, users, loan cancellation and balances',async t=>{const b=setup(t);manual(b);post(b,body(b,'m',{actualAmount:8000}));schedule(b);const id=settle(b,'principal');post(b,body(b,id,{},'cancelActual'));const backupDir=path.join(b.dir,'backups'),m=await createBackup({databasePath:b.store.filename,backupDir,statusDir:path.join(b.dir,'status')});assert.equal(m.schemaVersion,4);assert.equal(m.counts.transaction_revisions,2);const source=path.join(backupDir,m.databaseFile),sha=checksum(source),target=path.join(b.dir,'restored.sqlite');await restore(path.join(backupDir,m.id+'.manifest.json'),target);const r=openStore(target);try{for(const table of ['transaction_revisions','transaction_origins','cashflow_transactions','accounts','payment_schedule_legs','users'])assert.deepEqual(r.db.prepare('SELECT * FROM '+table+' ORDER BY 1').all(),b.store.db.prepare('SELECT * FROM '+table+' ORDER BY 1').all());assert.equal(ledger(r,{today:()=> '2026-12-31'}).get('getPaymentSchedules').data[0].principalRemaining,3850000);}finally{r.close();}assert.equal(checksum(source),sha);});
test('correction UI escapes content, keeps reviewed version and sends correction through the authenticated API',async t=>{
 const b=setup(t);manual(b,{description:'<img src=x onerror=bad()>',memo:'=1+1'});
 const {createFrontend}=require('./helpers.cjs'),f=createFrontend({get:b.api.get,post:p=>b.api.post(p,'admin')});
 f.context.crypto={randomUUID};let html='',closes=0;
 f.context.showModal=value=>html=value;f.context.closeModal=()=>closes++;
 f.context.loadCashflowMonth=async()=>{};
 f.run(fs.readFileSync(path.join(__dirname,'../assets/corrections.js'),'utf8'));
 await f.run("ActualCorrections.open('m')");assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<img/);
 f.node('ac_edit').onclick();assert.equal(closes,2);
 const original=b.store.find('cashflow_transactions','m');
 for(const [k,v]of Object.entries({actualDate:original.actualDate,actualAmount:'8000',type:'出金',account:'b',partner:'合成先',description:'訂正',memo:'合成',reason:'UI検証'}))f.node('ac_'+k).value=v;
 f.node('ac_basis').checked=false;await f.node('ac_review').onclick();assert.match(html,/最終確認/);assert.match(html,/8,000円/);assert.equal(b.store.find('cashflow_transactions','m').actualAmount,10000);
 await f.node('ac_save').onclick();assert.equal(b.store.find('cashflow_transactions','m').actualAmount,8000);assert.equal(b.store.find('cashflow_transactions','m').account,'b');assert.equal(b.api.get('getActualDetail',{id:'m'}).history[0].reason,'UI検証');
});
test('protected reopened plan cannot be changed by the generic form or deleted',t=>{const b=setup(t);manual(b);post(b,body(b,'m',{},'reopenActual'));const r=b.store.find('cashflow_transactions','m');assert.throws(()=>b.api.post({action:'saveTransaction',...r,plannedAmount:1,expectedUpdatedAt:r.updatedAt}),/元予定/);assert.throws(()=>b.api.post({action:'deleteRecord',id:'m',sheet:'cashflow_transactions',expectedUpdatedAt:r.updatedAt}),/物理削除/);});
test('cancelled loan history protects the loan baseline from subsequent parent edits',t=>{const b=setup(t);schedule(b,'combined');const id=settle(b,'total');post(b,body(b,id,{},'cancelActual'));const m=b.api.get('getPaymentSchedules').data[0];assert.throws(()=>b.api.post({action:'scheduleSave',...m,rows:[],requestId:randomUUID(),expectedVersion:m.version,principalOpeningBalance:1}),/基準/);});
