'use strict';
process.env.TZ='Asia/Tokyo';
const {test,afterEach}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {randomUUID}=require('node:crypto');
const {openStore}=require('../src/storage.cjs'),ledger=require('../src/domain/ledger.cjs'),math=require('../assets/cashflow-math.js');
const {createBackup,checksum}=require('../src/backup.cjs'),{restore}=require('../tools/restore.cjs');
const input=require('../assets/schedule-input.js');
const {createHash}=require('node:crypto');
const active=[];afterEach(()=>{for(const x of active.splice(0)){x.store.close();fs.rmSync(x.dir,{recursive:true,force:true});}});
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'schedule-test-')),store=openStore(path.join(dir,'db.sqlite'));let now='2026-09-28';const api=ledger(store,{today:()=>now});const ctx={dir,store,api,date:d=>now=d};active.push(ctx);api.post({action:'saveAccount',id:'a',bank:'合成銀行',type:'普通',balance:1000000,balanceDate:'2026-09-27'});return ctx;}
const request=(action,body)=>({action,requestId:randomUUID(),...body});
const payload=(more={})=>({id:'s',name:'合成借入',kind:'loan',account:'a',partner:'合成銀行',holidayRule:'none',defaultDebitMode:'split',principalStartMode:'existing',principalBalanceDate:'2026-09-30',principalOpeningBalance:3850000,rows:[{id:'r',nominalDate:'2026-10-31',plannedPrincipal:100000,plannedInterest:12345}],...more});
function current(b){return b.api.get('getPaymentSchedules',{id:'s'}).data[0];}
function saved(b,more={}){b.api.post(request('scheduleSave',payload(more)));return current(b);}
function confirm(b,part,more={}){const m=current(b),l=m.occurrences[0].legs.find(l=>l.component===part);return b.api.post(request('scheduleConfirm',{id:l.id,expectedVersion:m.version,actualDate:'2026-10-31',actualPrincipal:100000,actualInterest:12345,settled:true,...more}));}
test('split principal then interest: actual principal only reduces debt; account uses bank amount; finish only after both',()=>{const b=setup();saved(b);b.date('2026-11-01');confirm(b,'principal');let m=current(b);assert.equal(m.occurrences[0].status,'一部支払');assert.equal(m.principalRemaining,3750000);assert.equal(m.interestPaid,0);assert.equal(math.actualAt(b.store.find('accounts','a'),b.store.all('cashflow_transactions'),'2026-10-31'),900000);confirm(b,'interest');m=current(b);assert.equal(m.occurrences[0].status,'支払済');assert.equal(m.principalRemaining,3750000);assert.equal(m.interestPaid,12345);assert.equal(math.actualAt(b.store.find('accounts','a'),b.store.all('cashflow_transactions'),'2026-10-31'),887655);});
test('combined actual keeps breakdown and one bank transaction, actual variance explicitly allocated',()=>{const b=setup();saved(b,{defaultDebitMode:'combined'});b.date('2026-11-01');confirm(b,'total',{actualInterest:12000});const m=current(b);assert.equal(m.principalRemaining,3750000);assert.equal(m.interestPaid,12000);assert.equal(b.store.all('cashflow_transactions').length,1);assert.equal(b.store.all('cashflow_transactions')[0].actualAmount,112000);});
test('regular variable amounts, extension, final row and cancelled row',()=>{const b=setup();let m=saved(b,{kind:'lease',rows:[{id:'r',nominalDate:'2026-10-31',plannedAmount:123450}]});assert.equal(m.occurrences[0].legs.length,1);assert.equal(m.principalRemaining,null);b.api.post(request('scheduleSave',payload({kind:'lease',expectedVersion:m.version,rows:[{id:'r',nominalDate:'2026-10-31',plannedAmount:123450},{id:'r2',nominalDate:'2026-11-30',plannedAmount:122980}]})));m=current(b);assert.equal(m.occurrences.length,2);b.api.post(request('scheduleCancel',{id:'r2',expectedVersion:m.version}));assert.equal(current(b).occurrences[1].status,'取消');assert.equal(b.api.get('getTransactions',{month:'2027-01'}).data.length,0);});
test('per-occurrence exception and changing parent defaults does not mutate created occurrences',()=>{const b=setup();let m=saved(b,{defaultDebitMode:'combined',rows:[{id:'r',nominalDate:'2026-10-31',plannedPrincipal:100000,plannedInterest:12345,debitModeOverride:'split'}]});assert.equal(m.occurrences[0].legs.length,2);b.api.post(request('scheduleSave',payload({expectedVersion:m.version,defaultDebitMode:'split',rows:[]})));m=current(b);assert.equal(m.occurrences[0].effectiveDebitMode,'split');assert.equal(m.occurrences[0].debitModeOverride,'split');});
test('explicit future default propagation replaces topology, cancelled old legs stay cancelled on repeat',()=>{const b=setup();let m=saved(b,{defaultDebitMode:'combined'});const body=payload({expectedVersion:m.version,applyDefaults:true});b.api.post(request('scheduleSave',body));m=current(b);assert.equal(m.occurrences[0].legs.length,2);assert.equal(b.store.all('cashflow_transactions').filter(t=>t.status==='取消').length,1);b.api.post(request('scheduleSave',{...body,expectedVersion:m.version}));assert.equal(b.store.all('cashflow_transactions').length,3);});
test('per-row combined override changes only that row',()=>{const b=setup();let m=saved(b);b.api.post(request('scheduleSave',payload({expectedVersion:m.version,rows:[{...payload().rows[0],debitModeOverride:'combined'}]})));m=current(b);assert.equal(m.occurrences[0].legs.length,1);assert.equal(m.occurrences[0].legs[0].plannedAmount,112345);});
test('confirmed rows reject edits and parent loan basis changes; full save with unchanged paid rows allows extension',()=>{const b=setup();saved(b);b.date('2026-11-01');confirm(b,'principal');let m=current(b);assert.throws(()=>b.api.post(request('scheduleSave',payload({expectedVersion:m.version,rows:[{...payload().rows[0],plannedPrincipal:99999}]}))),/確定済み/);assert.throws(()=>b.api.post(request('scheduleSave',payload({expectedVersion:m.version,principalOpeningBalance:1,rows:[]}))),/基準/);b.api.post(request('scheduleSave',payload({expectedVersion:m.version,rows:[payload().rows[0],{id:'r2',nominalDate:'2026-12-31',plannedPrincipal:100000,plannedInterest:11000}]})));assert.equal(current(b).occurrences.length,2);});
test('interest only then principal, and partial cancellation is not paid',()=>{const b=setup();saved(b);b.date('2026-11-01');confirm(b,'interest');let m=current(b);assert.equal(m.principalRemaining,3850000);assert.equal(m.occurrences[0].status,'一部支払');b.api.post(request('scheduleCancel',{id:'r',expectedVersion:m.version}));assert.equal(current(b).occurrences[0].status,'一部支払・残予定取消');});
test('future unpaid leg may change after other component has settled, settled component protected',()=>{const b=setup();saved(b);b.date('2026-10-30');confirm(b,'principal',{actualDate:'2026-10-30'});let m=current(b),l=m.occurrences[0].legs.find(l=>l.component==='interest');b.api.post(request('scheduleEditLeg',{id:l.id,expectedVersion:m.version,plannedDate:'2026-11-02',plannedAmount:12000}));m=current(b);assert.equal(m.occurrences[0].plannedInterest,12000);assert.equal(m.principalRemaining,3750000);l=m.occurrences[0].legs.find(l=>l.component==='principal');assert.throws(()=>b.api.post(request('scheduleEditLeg',{id:l.id,expectedVersion:m.version,plannedDate:'2026-11-02',plannedAmount:12000})),/未実績/);});
test('new loan starts from original principal and date; basis day principal already absorbed',()=>{const b=setup();saved(b,{principalStartMode:'new',originalPrincipal:1000000,loanDate:'2026-10-31',principalBalanceDate:'2026-10-31',principalOpeningBalance:900000});b.date('2026-11-01');confirm(b,'principal');assert.equal(current(b).principalRemaining,900000);});
test('planned principal never reduces principal balance; before basis balance unavailable',()=>{const b=setup();saved(b);assert.equal(current(b).principalRemaining,null);b.date('2026-12-01');assert.equal(current(b).principalRemaining,3850000);});
test('idempotent save and confirmation; stale edit rejected; changed retry rejected',()=>{const b=setup(),p=request('scheduleSave',payload());b.api.post(p);assert.equal(b.api.post(p).duplicate,true);assert.equal(b.store.all('cashflow_transactions').length,2);assert.throws(()=>b.api.post({...p,name:'changed'}),/再送/);b.date('2026-11-01');const m=current(b),c=request('scheduleConfirm',{id:m.occurrences[0].legs[0].id,expectedVersion:m.version,actualDate:'2026-10-31',actualPrincipal:100000,actualInterest:12345,settled:true});b.api.post(c);assert.equal(b.api.post(c).duplicate,true);assert.throws(()=>b.api.post(request('scheduleSave',payload({expectedVersion:1}))),/更新/);});
test('invalid row rolls back entire master and generated legs',()=>{const b=setup();assert.throws(()=>saved(b,{rows:[payload().rows[0],{id:'bad',nominalDate:'2026-02-30',plannedPrincipal:1,plannedInterest:2}]}),/日付/);assert.equal(b.store.db.prepare('SELECT count(*) n FROM payment_schedules').get().n,0);assert.equal(b.store.all('cashflow_transactions').length,0);});
test('generated bank IDs never overwrite unrelated existing records',()=>{const b=setup(),tid='st_sl_'+createHash('sha256').update(JSON.stringify(['r',1,'principal'])).digest('hex').slice(0,40);b.api.post({action:'saveTransaction',id:tid,source:'manual',type:'出金',account:'a',plannedDate:'2026-10-31',plannedAmount:7});assert.throws(()=>saved(b),/重複/);assert.equal(b.store.find('cashflow_transactions',tid).plannedAmount,7);assert.equal(b.store.db.prepare('SELECT count(*) n FROM payment_schedules').get().n,0);});
test('schedule Excel workbook roundtrip retains numeric breakdown and literal untrusted strings',()=>{const b=setup(),m=saved(b,{name:'=1+1',partner:'<script>synthetic</script>'}),XLSX=require('../assets/vendor/xlsx.full.min.js'),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(input.exportRows(m)),'予定表');const result=XLSX.read(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),{type:'buffer'}),sheet=result.Sheets['予定表'];assert.equal(sheet.A2.v,'=1+1');assert.equal(sheet.A2.f,undefined);assert.ok(XLSX.utils.sheet_to_json(sheet,{header:1})[1].includes(100000));assert.deepEqual(input.parseAmounts('100,000\t12,345\n100000\t11980',true),[{plannedPrincipal:100000,plannedInterest:12345},{plannedPrincipal:100000,plannedInterest:11980}]);});
test('zero interest requires no phantom leg and completes with principal only',()=>{const b=setup();saved(b,{rows:[{...payload().rows[0],plannedInterest:0}]});b.date('2026-11-01');confirm(b,'principal');assert.equal(current(b).occurrences[0].status,'支払済');assert.equal(current(b).interestPaid,0);});
test('generic transaction endpoint cannot edit or delete schedule bank legs',()=>{const b=setup(),m=saved(b),t=b.store.find('cashflow_transactions',m.occurrences[0].legs[0].transactionId);assert.throws(()=>b.api.post({action:'saveTransaction',...t,source:'manual',plannedAmount:1,expectedUpdatedAt:t.updatedAt}));assert.throws(()=>b.api.post({action:'deleteRecord',sheet:'cashflow_transactions',id:t.id,expectedUpdatedAt:t.updatedAt}));assert.deepEqual(b.store.find('cashflow_transactions',t.id),t);});
test('backup integrity rejects a missing bank leg or a planned amount mismatch',()=>{const b=setup(),m=saved(b),l=m.occurrences[0].legs[0],check=require('../src/domain/schedules.cjs').checkIntegrity;b.store.db.prepare('UPDATE cashflow_transactions SET plannedAmount=1 WHERE id=?').run(l.transactionId);assert.throws(()=>check(b.store.db),/整合性/);b.store.db.prepare('UPDATE cashflow_transactions SET plannedAmount=? WHERE id=?').run(l.plannedAmount,l.transactionId);check(b.store.db);b.store.db.prepare('DELETE FROM payment_schedule_legs WHERE id=?').run(l.id);assert.throws(()=>check(b.store.db),/整合性/);});
test('holiday adjustment and year crossing use existing bank calendar',()=>{const b=setup();const d=b.api.get('previewScheduleDates',{start:'2026-10',count:'4',day:'last',rule:'next'}).data;assert.deepEqual(d.map(x=>x.paymentDate),['2026-11-02','2026-11-30','2027-01-04','2027-02-01']);assert.equal(b.api.get('previewScheduleDates',{start:'2027-02',count:1,day:'31',rule:'none'}).data[0].nominalDate,'2027-02-28');saved(b,{holidayRule:'next',rows:[{...payload().rows[0],nominalDate:'2026-12-31'}]});assert.equal(current(b).occurrences[0].paymentDate,'2027-01-04');});
test('input parsing validates dates, amounts, principal total and rejects formulas/yearless date',()=>{assert.equal(input.parse('2026/10/31\t100,000\t12,345',true)[0].plannedPrincipal,100000);assert.equal(input.parse('2026/11/30\t122,980',false)[0].plannedAmount,122980);for(const s of ['10/31\t100','2026/02/30\t100','2026/10/31\t=1+1','2026/10/31\t-1'])assert.throws(()=>input.parse(s,false));});
test('Excel detail and cashflow period reflect one combined versus two split lines without double counting',()=>{const b=setup();let m=saved(b);b.date('2026-11-01');confirm(b,'principal');m=current(b);const out=input.exportRows(m);assert.equal(out.length,2);assert.equal(out[1][9],100000);assert.equal(out[1][10],0);assert.equal(out[1][12],'2026-10-31');const period=b.api.get('getCashflowPeriod',{start:'2026-10',end:'2026-10',accounts:'a',mode:'actual',day:'2026-11-01'}).periods[0];assert.equal(period.rows.length,1);assert.equal(period.totals.a.expense,100000);assert.equal(period.totals.a.closing,900000);});
test('backup and real backup restoration preserve loan basis, split actual, unpaid interest, users and references',async()=>{const b=setup();saved(b);b.date('2026-11-01');confirm(b,'principal');b.store.db.prepare("INSERT INTO users VALUES('u','synthetic','synthetic-hash','admin','2026-09-28')").run();const backupDir=path.join(b.dir,'backups'),m=await createBackup({databasePath:b.store.filename,backupDir,statusDir:path.join(b.dir,'status')});const source=path.join(backupDir,m.databaseFile),before=checksum(source),target=path.join(b.dir,'restored.sqlite');await restore(path.join(backupDir,m.id+'.manifest.json'),target);assert.equal(checksum(source),before);const r=openStore(target);try{const l=ledger(r,{today:()=> '2026-11-01'});assert.deepEqual(l.get('getPaymentSchedules'),b.api.get('getPaymentSchedules'));assert.equal(r.db.prepare('SELECT count(*) n FROM users').get().n,1);assert.equal(r.db.prepare('PRAGMA foreign_key_check').all().length,0);}finally{r.close();}});

